apiVersion: v1
kind: ConfigMap
metadata:
 name: aws-auth
 namespace: kube-system
data:
 mapRoles: |
   - rolearn:  arn:aws:iam::191007734411:role/eksctl-my-cluster-nodegroup-ng-14-NodeInstanceRole-JMT5EZVMHSRP
     username: system:node:{{EC2PrivateDNSName}}
     groups:
       - system:bootstrappers
       - system:nodes